# Validate commit messages
commit-msg:
  commands:
    check-branch:
      #   run: bun commit:protect
      # 'lint commit message':
      run: bunx commitlint --edit {1}

pre-commit:
  jobs:
    group:
      name: lint
      run: bun lint
      stage_fixed: true
    sort:
      run: bun sort
      stage_fixed: true
    build:
      run: bun build

post-merge:
  commands:
    install-deps-postmerge:
      run: pnpx install-deps-postmerge
      tags: frontend
