# JSON Schema
# @see https://gist.github.com/dankreiger/dedf33c6d0bc5a6e2ba23684def02535

# Validate commit messages
commit-msg:
  commands:
    check-branch:
      run: bun commit:protect
    "lint commit message":
      run: bunx commitlint --edit {1}

pre-commit:
  jobs:
    group:
      name: lint and format (biome check)
      run: bun run check:fix
      stage_fixed: true
    sort:
      run: bun sort
      stage_fixed: true
    build:
      run: bun build

post-merge:
  commands:
    install-deps-postmerge:
      run: |
        # capture info messages and any errors in a log file
        exec >> log/hooks-out.log 2>&1

        if git diff-tree --name-only --no-commit-id ORIG_HEAD HEAD | grep -q 'package.json'; then
          echo "$(date): reinstalling deps since package.json changed"
          yarn > /dev/null
        else
          echo "$(date): no changes detected in package.json"
        fi

        # link is needed: ln -fv [script location] .git/hooks/
